### ISSUE TITLE
#Bugs for Edge (1.getRervation回傳資料格式不正確 2.diagnosisInfo沒正確寫入資料庫)

### ISSUE THREAD

**Issue by jameslu216** [jameslu216/vetechToB#1]
前提，目前master專案已經確認，使用者在預約頁進行預約後，能正確在資料庫寫入一個預約

Q1. getReservation api 會回傳不正確的格式
![image](https://user-images.githubusercontent.com/56047484/120920495-b0c43a00-c6f1-11eb-816f-1624012dec92.png)
![image](https://user-images.githubusercontent.com/56047484/120920517-c33e7380-c6f1-11eb-8c3e-41941c444dac.png)

Q2. getDiagnosisinfo api 在有正確預約的前提下，沒有回傳該日醫生看診時間
![image](https://user-images.githubusercontent.com/56047484/120920527-d0f3f900-c6f1-11eb-8fa5-777c7b267053.png)

**Comment by jack111331** [comment]
35053dd fix first problem

**Comment by jack111331** [comment]
d5f3e4b fix whole problem
