### ISSUE TITLE
在有api_token的狀況下預約 (/reservation/create) 時會報500

### ISSUE THREAD

**Issue by jameslu216** [jameslu216/vetechToB#2]
![image](https://user-images.githubusercontent.com/56047484/121769823-5b2bd980-cb98-11eb-8f2f-54f74d5efd31.png)
先前討論的結果為
前端時間的格式傳 "date":"2020-6-1 15:30"      後端接的方法為 "date":"2020-6-1" "time":"15:30" 
經決議後交由後端改

**Comment by jack111331** [comment]
@jameslu216  b82c1da fix the bug
