### ISSUE TITLE
取得預約(/reservation)   會報錯 500 

### ISSUE THREAD

**Issue by jameslu216** [jameslu216/vetechToB#4]
附上環境資訊

![image](https://user-images.githubusercontent.com/56047484/121770243-dbebd500-cb9a-11eb-96d9-0967b02e3cdc.png)

![image](https://user-images.githubusercontent.com/56047484/121770262-f2922c00-cb9a-11eb-984f-0b6b2fc5106a.png)
![image](https://user-images.githubusercontent.com/56047484/121770240-d3939a00-cb9a-11eb-93a2-4f56ea11eac6.png)
![image](https://user-images.githubusercontent.com/56047484/121770274-fe7dee00-cb9a-11eb-802c-3680b6902d2e.png)

**Comment by jack111331** [comment]
@jameslu216 711849d fix the bug
